# Site settings
title: KJW3, LLC - Cloud Consulting
email: kevin@kjw3.com
description: > # this means to ignore newlines until "baseurl:"
  Cloud computing is not new. However, that doesn't make it easier to adopt.
  Let us help your business determine the proper use cases for cloud computing.
  Run by a certified Amazon Web Services Solution Architect and an OpenStack
  advocate, we will make your cloud migration a success.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kjw3.com" # the base hostname & protocol for your site
twitter_username: kjwthree
github_username:  kjw3

# Build settings
markdown: kramdown
