# Site settings
title: KJW3, LLC - Technology Consulting
email: kevin@kjw3.llc
description: > # this means to ignore newlines until "baseurl:"
  Technology consulting in a world of clouds and artificial intelligence.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kjw3.llc" # the base hostname & protocol for your site
github_username:  kjw3

# Build settings
markdown: kramdown
